/* QBR V11 - inspect real administration schema. READ ONLY. */
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='qbr'
  AND TABLE_NAME IN ('AppUser','UserTrackAccess','TowerTrack')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
